spawn:
  world: "world"
  x: 0
  y: 50
  z: 0
  pitch: 90
  yaw: 0
generators:
  # List of block types that act as generators when broken
  # Use the Bukkit Material names, comma-separated
  allowed-blocks: "DIAMOND_ORE,GOLD_ORE,IRON_ORE,COAL_ORE,LAPIS_ORE,EMERALD_ORE,REDSTONE_ORE,COPPER_ORE,NETHER_GOLD_ORE,NETHER_QUARTZ_ORE,ANCIENT_DEBRIS,SPAWNER"
messages:
  reload: "<green>Configuration reloaded successfully!"
  spawn: "<yellow>Teleported to Spawn!"
